FROM ubuntu:22.04

ENV DEBIAN_FRONTEND="noninteractive"
RUN apt update && \
    apt install -y pipx && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# SHELL ["/bin/bash", "--login", "-c"]
# RUN pipx ensurepath

# RUN PIPX_BIN_DIR=/usr/local/bin pipx install meson

ENV PIPX_BIN_DIR="/usr/local/bin"
RUN pipx install meson

RUN meson
